<!DOCTYPE html>
<html lang="fr">

<head>

	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title><?php echo htmlspecialchars($title) ?></title>
	<!-- CSS Vendor -->
	<link rel="stylesheet" href="css/fontawesome.min.css" />
	<link rel="stylesheet" href="css/normalize.css" />
	<!-- CSS Font -->
	<link href="https://fonts.googleapis.com/css?family=Laila|Charm|Srisakdi|Slabo+27px" rel="stylesheet">
	<!-- CSS Perso -->
	<link rel="stylesheet" href="dart-sass/css/style.css" />
	<!-- Librairie jQuery -->
	<script src="js/jquery-3.3.1.min.js"></script>
</head>

<body>
	<!--HEADER-->
	<header>
		<nav>
			<a class="headerLogo" href="index.php"><img src="images/logo2.png" alt="logo" title="Retour à l'accueil"></a>
			<i class="fas fa-bars"></i>
			<div class="hideHeaderMenu">
				<a href="index.php">Accueil</a>
				<a href="#">Contact</a>
				<a href="#">Qui sommes nous ?</a>
				<a href="gallery.php">Galerie</a>
			</div>
		</nav>
	</header>

<main>
